language: ruby
before_install: gem install bundler -v 1.11.2
script: "bundle exec rspec spec"
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2
notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com
