language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ruby-dev libgmp3-dev
  - gem install bundler -v 1.13.5
script: "bundle exec rspec spec"
rvm:
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head

notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com
