language: ruby
before_install:
  - gem install bundler -v 1.13.5
script: "bundle exec rspec spec"
rvm:
  - 2.2.5
  - ruby-head
  - jruby-9.1.2.0
matrix:
  allow_failures:
    - rvm: rbx-2

notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com
