language: ruby
before_install:
  - gem install bundler -v 1.13.5
script: "bundle exec rspec spec"
rvm:
  - 2.2.5
  - ruby-head
  - rbx-2
  - jruby-head
notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com
